// Code generated by scripts/gen (custom_criteria_ext.go.tmpl). DO NOT EDIT.

// ---- adcp fork: CustomCriteria xsi:type polymorphism fix ----
// Rendered into each generated service package whose CustomCriteriaSet a caller
// marshals. GAM's customTargeting tree is document/literal SOAP with an abstract
// CustomCriteriaNode child type: every child of a CustomCriteriaSet must name its
// concrete subtype via an xsi:type attribute. gowsdl models this as
// `Children []*CustomCriteriaNode` (an empty base struct) with no xsi:type
// emission, so a concrete node can neither be stored in the slice nor serialized
// in the shape GAM accepts. scripts/generate.sh retypes that field to
// []CustomCriteriaChild, and the marshalers below supply the xsi:type wire shape,
// mirroring actions.go's xsiTypedAction for abstract *Action args. Confirmed
// against the live test network; guarded by the adcp sdktest package (see
// gam-p0-findings.md).

package forecast_service

import "encoding/xml"

// xsiSchemaInstanceNS is the XML Schema instance namespace whose "type"
// attribute selects a concrete subtype for an element declared as an abstract
// base type.
const xsiSchemaInstanceNS = "http://www.w3.org/2001/XMLSchema-instance"

// CustomCriteriaChild is implemented by the concrete node types that may appear
// in CustomCriteriaSet.Children. The method is unexported, so only this package's
// node types can satisfy it — callers build trees from these types alone.
type CustomCriteriaChild interface {
	marshalAsCustomCriteriaChild(e *xml.Encoder) error
}

// customCriteriaChildStart is the <children> start element naming a concrete
// subtype via xsi:type (with the xsi namespace declared on the element, as
// actions.go does — namespace-aware parsers resolve xsi by URI, not prefix).
func customCriteriaChildStart(concreteType string) xml.StartElement {
	return xml.StartElement{
		Name: xml.Name{Local: "children"},
		Attr: []xml.Attr{
			{Name: xml.Name{Local: "xmlns:xsi"}, Value: xsiSchemaInstanceNS},
			{Name: xml.Name{Local: "xsi:type"}, Value: concreteType},
		},
	}
}

// Each leaf child marshals through an alias, which strips methods so
// EncodeElement reflects over the fields rather than recursing into a marshaler.
func (c *CustomCriteria) marshalAsCustomCriteriaChild(e *xml.Encoder) error {
	type alias CustomCriteria
	return e.EncodeElement((*alias)(c), customCriteriaChildStart("CustomCriteria"))
}

func (c *CmsMetadataCriteria) marshalAsCustomCriteriaChild(e *xml.Encoder) error {
	type alias CmsMetadataCriteria
	return e.EncodeElement((*alias)(c), customCriteriaChildStart("CmsMetadataCriteria"))
}

func (c *AudienceSegmentCriteria) marshalAsCustomCriteriaChild(e *xml.Encoder) error {
	type alias AudienceSegmentCriteria
	return e.EncodeElement((*alias)(c), customCriteriaChildStart("AudienceSegmentCriteria"))
}

func (s *CustomCriteriaSet) marshalAsCustomCriteriaChild(e *xml.Encoder) error {
	return s.encodeCustomCriteriaSet(e, customCriteriaChildStart("CustomCriteriaSet"))
}

// MarshalXML emits a CustomCriteriaSet as an element-only complex type: a
// logicalOperator followed by each child wrapped in an xsi:type-named <children>
// element. Used for the top-level <customTargeting> (a concrete CustomCriteriaSet
// that needs no xsi:type of its own) and, via marshalAsCustomCriteriaChild, for
// nested sets.
func (s CustomCriteriaSet) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return (&s).encodeCustomCriteriaSet(e, start)
}

func (s *CustomCriteriaSet) encodeCustomCriteriaSet(e *xml.Encoder, start xml.StartElement) error {
	if err := e.EncodeToken(start); err != nil {
		return err
	}
	if s.LogicalOperator != nil {
		if err := e.EncodeElement(string(*s.LogicalOperator), xml.StartElement{Name: xml.Name{Local: "logicalOperator"}}); err != nil {
			return err
		}
	}
	for _, child := range s.Children {
		if child == nil {
			continue
		}
		if err := child.marshalAsCustomCriteriaChild(e); err != nil {
			return err
		}
	}
	return e.EncodeToken(start.End())
}

// customCriteriaError is a decode-side error string. The generated package's
// imports are minimal, so this local error type keeps the file dependency-light.
type customCriteriaError string

func (e customCriteriaError) Error() string { return string(e) }

// UnmarshalXML reconstructs a CustomCriteriaSet from a GAM SOAP response. The
// encoding/xml package cannot decode into the abstract []CustomCriteriaChild
// slice on its own, so this walks the set's child tokens and dispatches every
// <children> element by its xsi:type attribute to the matching concrete node,
// recursing (through this same method) for nested sets. Without it a getLineItems
// -> modify -> updateLineItems round-trip would silently drop all custom
// targeting: the inbound half of the polymorphism gap MarshalXML fixes outbound.
func (s *CustomCriteriaSet) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch t := tok.(type) {
		case xml.StartElement:
			switch t.Name.Local {
			case "logicalOperator":
				var op CustomCriteriaSet_LogicalOperator
				if err := d.DecodeElement(&op, &t); err != nil {
					return err
				}
				s.LogicalOperator = &op
			case "children":
				child, err := newCustomCriteriaChild(t)
				if err != nil {
					return err
				}
				if err := d.DecodeElement(child, &t); err != nil {
					return err
				}
				s.Children = append(s.Children, child)
			default:
				// Unknown element: skip its whole subtree.
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			if t.Name == start.Name {
				return nil
			}
		}
	}
}

// newCustomCriteriaChild instantiates the concrete node named by a <children>
// element's xsi:type attribute. The attribute is matched namespace-aware — by URI
// (xsiSchemaInstanceNS) and local name "type" — never by the literal "xsi:"
// prefix, which a namespace-aware decoder is free to rewrite. Any prefix up to and
// including the last ":" is stripped before dispatch. A missing or unrecognized
// xsi:type is a hard error: silently skipping the child is the exact silent-drop
// bug this fix exists to prevent.
func newCustomCriteriaChild(start xml.StartElement) (CustomCriteriaChild, error) {
	typeName := ""
	found := false
	for _, attr := range start.Attr {
		if attr.Name.Space == xsiSchemaInstanceNS && attr.Name.Local == "type" {
			typeName = stripXMLPrefix(attr.Value)
			found = true
			break
		}
	}
	if !found {
		return nil, customCriteriaError("custom criteria <children> element is missing its xsi:type attribute")
	}
	switch typeName {
	case "CustomCriteria":
		return &CustomCriteria{}, nil
	case "CmsMetadataCriteria":
		return &CmsMetadataCriteria{}, nil
	case "AudienceSegmentCriteria":
		return &AudienceSegmentCriteria{}, nil
	case "CustomCriteriaSet":
		return &CustomCriteriaSet{}, nil
	default:
		return nil, customCriteriaError("custom criteria <children> element has unrecognized xsi:type " + typeName)
	}
}

// stripXMLPrefix removes any namespace prefix (up to and including the last ":")
// from an xsi:type value, e.g. "ns1:CustomCriteria" -> "CustomCriteria".
func stripXMLPrefix(s string) string {
	for i := len(s) - 1; i >= 0; i-- {
		if s[i] == ':' {
			return s[i+1:]
		}
	}
	return s
}
