#!/usr/bin/env bash
set -euo pipefail

# Go module name — must match go.mod
MODULE="github.com/jfrconley/google-admanager-api-go"

# ---------- Configuration ----------
# Add or remove versions / services here.

VERSIONS=(
  "v202602"
  "v202505"
)

SERVICES=(
  "NetworkService"
  "OrderService"
  "LineItemService"
  "CompanyService"
  "CreativeService"
  "CreativeSetService"
  "InventoryService"
  "ReportService"
  "UserService"
  "ForecastService"
  "CustomTargetingService"
  "LineItemCreativeAssociationService"
  "PlacementService"
  "PublisherQueryLanguageService"
  "NativeStyleService"
)

# ---------- Helpers ----------

# Convert CamelCase to snake_case.
to_snake_case() {
  echo "$1" \
    | sed -E 's/([A-Z])/_\1/g' \
    | sed 's/^_//' \
    | tr '[:upper:]' '[:lower:]'
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Fix structs where an embedded type name collides with a field name.
# gowsdl generates e.g.:
#   type BooleanValue struct {
#       *Value
#       Value bool `xml:"value,omitempty"...`
#   }
# Go rejects this because *Value and field Value share the same name.
# The base Value type is always an empty struct, so dropping the embed is safe.
fix_embedded_conflicts() {
  local file="$1"
  # perl -i (not `sed -i`) for portability: BSD sed requires an extension arg
  # after -i and does not treat \t as a tab, so `sed -i '/^\t\*Value$/d'` fails
  # on macOS. perl's -i and \t behave identically on macOS and Linux.
  perl -i -ne 'print unless /^\t\*Value$/' "$file"
  echo "  Fixed embedded *Value conflicts in $(basename "$file")"
}

# Retype GAM's DateTime/Date fields from the flat scalars gowsdl emits
# (soap.XSDDateTime / soap.XSDDate) to the generated element-only complex
# structs (*DateTime / *Date). GAM's WSDL declares these as complexTypes, but
# gowsdl maps them to xsd scalars; the live SOAP endpoint then rejects the flat
# wire shape with a "cvc-complex-type.2.3 ... element-only" fault. The complex
# DateTime/Date structs ARE generated (just never referenced as field types),
# so the retype is safe. Guarded on the struct existing in the file, so a
# package that lacks the complex type is left untouched.
# Verified against the live test network; regression-guarded by the sdktest
# package (see /gam-p0-findings.md #1). Uses perl -i for the same BSD/GNU
# portability reason as fix_embedded_conflicts above.
fix_datetime_types() {
  local file="$1"
  grep -q '^type DateTime struct' "$file" && perl -i -pe 's/\bsoap\.XSDDateTime\b/*DateTime/g' "$file"
  grep -q '^type Date struct' "$file" && perl -i -pe 's/\bsoap\.XSDDate\b/*Date/g' "$file"
  gofmt -w "$file"
  echo "  Retyped DateTime/Date fields to complex types in $(basename "$file")"
}

# ---------- Generate ----------

for version in "${VERSIONS[@]}"; do
  version_dir="${ROOT_DIR}/services/${version}"
  mkdir -p "${version_dir}"

  # --- Generate gowsdl service clients ---
  for service in "${SERVICES[@]}"; do
    pkg=$(to_snake_case "${service}")

    echo "Generating ${service} for ${version} (package: ${pkg})..."
    go tool gowsdl \
      -d "${version_dir}" \
      -o "${pkg}.go" \
      -p "${pkg}" \
      "https://ads.google.com/apis/ads/publisher/${version}/${service}?wsdl"

    generated_file="${version_dir}/${pkg}/${pkg}.go"
    if [[ -f "${generated_file}" ]]; then
      fix_embedded_conflicts "${generated_file}"
      fix_datetime_types "${generated_file}"
    fi
  done

  # --- Generate per-version client.go with service wrappers ---
  imports=""
  wrappers=""
  for service in "${SERVICES[@]}"; do
    pkg=$(to_snake_case "${service}")
    # Strip trailing "Service" to get the short name (e.g. "LineItem")
    short="${service%Service}"
    imports="${imports}"$'\n'"	\"${MODULE}/services/${version}/${pkg}\""
    wrappers="${wrappers}
// New${short}Service creates a ${service} client for API version ${version}.
func New${short}Service(c *admanager.Client) ${pkg}.${service}Interface {
	return ${pkg}.New${service}Interface(NewService(c, \"${service}\"))
}
"
  done

  cat > "${version_dir}/client.go" <<GOEOF
// Code generated by scripts/generate.sh. DO NOT EDIT.

package ${version}

import (
	admanager "${MODULE}"
	"github.com/hooklift/gowsdl/soap"
${imports}
)

// Version is the Ad Manager API version this package targets.
const Version = "${version}"

// NewService returns a *soap.Client configured for the given service name
// (e.g. "NetworkService") under API version ${version}.
func NewService(c *admanager.Client, serviceName string) *soap.Client {
	return admanager.NewServiceClient(c, Version, serviceName)
}
${wrappers}
GOEOF

  echo "Generated ${version_dir}/client.go"
done

echo ""
echo "Generation complete. Run 'go mod tidy' to update dependencies."
